apiVersion: v1
kind: Service
metadata:
  labels:
    app: agri-app-master
  name: svc-agri-app-master
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: agri-app-master
  type: LoadBalancer
status:
  loadBalancer: {}