apiVersion: v1
metadata:
  name: envs-config
data:
  PD_HOST: svc-agri-app-rs
  PD_PORT: "8001"
  TH_HOST: ur-web-app-lb
  TH_PORT: "8002"
kind: ConfigMap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agri-app-master
  name: agri-app-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-app-master
  strategy: {}
  template:
    metadata:
      labels:
        app: agri-app-master
    spec:
      containers:
      - args:
        - agri_app_master
        image: dhaura/agri-app-master-new:latest-x64
        name: master
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: envs-config
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: svc-agri-app-master
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: agri-app-master

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-agri-app
spec:
  ingressClassName: nginx
  rules:
# - host: myapp.com
#   http:
#      paths:
#         backend:
#           service:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-agri-app-master
            port:
              number: 80
      - path: /predict_disease
        pathType: Prefix
        backend:
          service:
            name: svc-agri-app-master
            port:
              number: 80
      - path: /read_temperature/(\d+)$
        pathType: Prefix
        backend:
          service:
            name: svc-agri-app-master
            port:
              number: 80
      - path: /read_humidity/(\d+)$
        pathType: Prefix
        backend:
          service:
            name: svc-agri-app-master
            port:
              number: 80
